name: dispatch receiver

on: [repository_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      if: github.event.action == 'making-framework'
      run: |
        cd ./source
        sh ./build_xcframework.sh
