name: dispatch receiver

on: [repository_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: dispatch trigger
      if: github.event.action == 'making-framework'
      run: |
        cd ./source
        sh ./build_xcframework.sh
